spring.application.name=registryservice
server.port=8080

# Hardcode the URI directly (Remove the ${} for this test)
spring.data.mongodb.uri=mongodb+srv://12230028gcit_db_user:iIaMZbTcupB5kBOw@cluster0.eclmltd.mongodb.net/NSPS_DB?retryWrites=true&w=majority
spring.data.mongodb.database=NSPS_Auth_DB

# Reduce timeout so you don't wait 30 seconds for failures
spring.data.mongodb.connect-timeout=5000